endpoints:
  - name: devlocalhost                 # Name of your endpoint, can be anything
    url: "http://localhost:9080/api/v1/status"
    interval: 5m                  # Duration to wait between every status check (default: 60s)
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[BODY].status == success"     # The json path "$.status" must be equal to UP
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: app.truccoinswap.com                 # Name of your endpoint, can be anything
    url: "http://app.truckcoinswap.com/api/v1/status"
    interval: 5m                  # Duration to wait between every status check (default: 60s)
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[RESPONSE_TIME] < 1500"   # Response time must be under 300ms
ui:
  header: "TCS App Status"
  logo: "img/logo.svg"

web:
  port: 15221
  address: "127.0.0.1"

